module.exports = {
  env: {
    FUNCTIONS_URL: process.env.FUNCTIONS_URL,
    FUNCTIONS_AUTH: process.env.FUNCTIONS_AUTH,
    HTTPS_URL: process.env.HTTPS_URL,
    DOCS_REPOSITORY_URL: process.env.DOCS_REPOSITORY_URL,
    DOCS_URL: process.env.DOCS_URL,
    GITHUB_ORG_NAME: process.env.GITHUB_ORG_NAME,
    FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
    FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSEGING_SENDER_ID: process.env.FIREBASE_MESSEGING_SENDER_ID,
    FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,
    FIREBASE_MEASUREMENT_ID: process.env.FIREBASE_MEASUREMENT_ID,
    GTM_ID: process.env.GTM_ID,
    GA_TRACKING_ID: process.env.GA_TRACKING_ID,
    STORAGE_SIZE_LIMIT: process.env.STORAGE_SIZE_LIMIT,
  },
  images: { domains: ['localhost', 'avatars.githubusercontent.com'] },
};
